### ISSUE TITLE
Filters panel scrolling indication

### ISSUE THREAD

**Issue by mrbkt** [kestreltechnology/electron-kt-advance#10]
Could the filters panel indicate that the columns have scrollable content?  Looking at the panel when it is first presented, the user has no indication there is more content available.  It is only when he accidentally scrolls on the column when the scroll bar presents itself briefly.  One idea would be to force the scroll bar to be always visible.  Another would be to provide an arrow suggesting content is available below.  

![screen shot 2017-04-17 at 10 11 38 am](https://cloud.githubusercontent.com/assets/1465947/25093111/5c3696ba-2356-11e7-9ab1-be78dc15ee7d.png)

**Comment by compartia** [comment]
Another idea is to render them all in several columns (probably there's enough space for it).
I'm also not happy about the current representation, and I'm planning to fix it after adding all the planned filtering options (like "select all", filter by complexity, etc..).

**Comment by compartia** [comment]
<img width="866" alt="screen shot 2017-05-08 at 21 12 40" src="https://cloud.githubusercontent.com/assets/7677437/25805686/257b0a0a-3433-11e7-8f67-16d5f92eed86.png">

**Comment by mrbkt** [comment]
Nicely done.
