### ISSUE TITLE
Filtering intuition

### ISSUE THREAD

**Issue by mrbkt** [kestreltechnology/electron-kt-advance#11]
It may be rocket noise history affecting my brain, but I found the filters dialog counter-intuitive owing to the verb "filter" used with the check boxes.   Selecting a check box to filter suggests omitting that item from the content, but that is in fact the opposite of the result.   After working out this response, then the colored and muted text makes sense and we ignore the panel title.  So perhaps changing the title would help.  I suggest "Select Proof Obligations" (or even "Select Content") and likewise modifying "filtered-out" to "deselected" or "not selected".  Another choice might be "Include Proof Obligations" with "not included", or "Show Proof Obligations" with "not shown".  

![screen shot 2017-04-17 at 10 26 23 am](https://cloud.githubusercontent.com/assets/1465947/25093532/55af19dc-2358-11e7-9534-6af0ec8fd136.png)

**Comment by compartia** [comment]
Yes, the word "filtering" is definitely about removing something. I do agree that from logics point of view there's a misuse of this term.
However, for me it is difficult to say what most users are custom to. For instance, Airbnb's approach to filtering (below) is similar to our current implementation. (Unfortunately, these big companies induce users' habits, and therefore, an "intuitive" UI is not something "good", but rather somewhat similar to Apple's, Google's .. etc )

Shortly, I personally like the "Include Proof Obligations" option.

<img width="574" alt="screen shot 2017-04-17 at 23 47 57" src="https://cloud.githubusercontent.com/assets/7677437/25094274/f19d5dde-23c8-11e7-996a-a90eea36b6eb.png">;

**Comment by mrbkt** [comment]
I'm happy to close this one since about PR#20 or so.
